# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
require 'time'

Tune.create(name: "The Kesh", rhythm: "Jig", alt_name: "Castel, Kincora")
Tune.create(name: "Blarney Pilgrim", rhythm: "Jig")
Tune.create(name: "Calliope House", rhythm: "Jig")
Tune.create(name: "Swallowtail", rhythm: "Jig")
Tune.create(name: "Mouse In The Kitchen", rhythm: "Jig")
Tune.create(name: "Morrison's", rhythm: "Jig")
Tune.create(name: "Father O'Flynn", rhythm: "Jig")

Tune.create(name: "A Fig For A Kiss", rhythm: "Slip Jig")
Tune.create(name: "Butterfly", rhythm: "Slip Jig")
Tune.create(name: "Kid on The Mountain", rhythm: "Slip Jig")
Tune.create(name: "Foxhunter's", rhythm: "Slip Jig")

Tune.create(name: "Wise Maid", rhythm: "Reel")
Tune.create(name: "Christmas Eve", rhythm: "Reel")
Tune.create(name: "Congress", rhythm: "Reel")
Tune.create(name: "Drowsy Maggie", rhythm: "Reel")
Tune.create(name: "Wind That Shakes The Barley", rhythm: "Reel")
Tune.create(name: "Gravel Walks", rhythm: "Reel")
Tune.create(name: "Sliver Spear", rhythm: "Reel")
Tune.create(name: "Toss The Feather", rhythm: "Reel")
Tune.create(name: "Toss The Feather", rhythm: "Reel")

Tune.create(name: "Belfast", rhythm: "Hornpipe")
Tune.create(name: "Cronin's", rhythm: "Hornpipe")
Tune.create(name: "Rights Of Man", rhythm: "Hornpipe")
Tune.create(name: "Off To California", rhythm: "Hornpipe")

Tune.create(name: "John Ryan", rhythm: "Polka")
Tune.create(name: "Egan's", rhythm: "Polka")
Tune.create(name: "Bill Sullivan's", rhythm: "Polka")
Tune.create(name: "Tom Sullivan's", rhythm: "Polka")

Tune.create(name: "Fanny Power", rhythm: "Waltz")
Tune.create(name: "Si beag Si mor", rhythm: "Waltz")
Tune.create(name: "Planxty Irwin", rhythm: "Waltz")
Tune.create(name: "South Wind", rhythm: "Waltz")
Tune.create(name: "Inisheer", rhythm: "Waltz")

Tune.create(name: "Down By The Sally Garden", rhythm: "Air")

User.create(name: "関西アイリッシュセッション", pref: "大阪", date: "第3土曜日　21時〜", login_id: "ksis", password: "kansaiyd", password_confirmation: "kansaiyd")
User.create(name: "関東アイルランド音楽セッション会", pref: "東京", date: "毎週水曜日の夜(時間不定)", login_id: "eims", password: "kantou23", password_confirmation: "kantou23")
User.create(name: "南日本アイルランド音楽会", pref: "九州", date: "月1回", login_id: "sjim", password: "enjoy", password_confirmation: "enjoy")
User.create(name: "アイル・セッション・イン・北日本", pref: "北海道", date: "不定期", login_id: "iinn", password: "hokuai", password_confirmation: "hokuai")
User.create(name: "ゲスト", pref:"未定", date: "不定期", login_id: "guest", password: "guest", password_confirmation: "guest")

Note.create(tune_id: 1, user_id: 1, status:"public", key: "G", scale: "major", abc:"T: The Kesh\nR: jig\nM: 6/8\nL: 1/8\nK: Gmaj\n|:G3 GAB|A3 ABd|edd gdd|edB dBA|\nGAG GAB|ABA ABd|edd gdd|BAF G3:|\n|:B2B d2d|ege dBA|B2B dBG|ABA AGA|\nBAB d^cd|ege dBd|gfg aga|bgg g3:|")
Note.create(tune_id: 1, user_id: 3, status:"draft", key: "A", scale: "major", abc:"T: The Kesh\nR: jig\nM: 6/8\nL: 1/8\nK: Gmaj\n|:G2D GAB|A2G ABd|ede gdB|B2G G2D|\nG2D GAB|A2G ABd|ede gdB|B2A G3:|\n|:Bgg dgg|Bgg dgg|Bgg dgg|B2G AGE|\nBgg dgg|~g2e d3|g3 a3|1 bgg g3:|2 bgg B2A||")
Note.create(tune_id: 1, user_id: 4, status:"draft", key: "D", scale: "major", abc:"T: The Kesh\nR: jig\nM: 6/8\nL: 1/8\nK: Dmaj\nA,|:D3 DEF|E3 EFA|BAA dAA|BAF AFE|\nD3 DEF|E3 EFA|BAA dAF|EDC D3:|\n|:{E}F3 AFA|BdB BAF|{E}F3 AFD|EFE EDE|\n{E}F3 AFA|BdB B2B| dcd ede|fdc d3:|")
Note.create(tune_id: 1, user_id: 2, status:"public", key: "D", scale: "major", abc:"T: The Kesh\nR: jig\nM: 6/8\nL: 1/8\nK: Gmaj\nD|:~G3 GAB|~A3 AB/c/d|edd gdd|edB dBA|\n~G3 GAB|~A3 ABd|edd gdB|1 AGF G2D:|2 AGF G2A||\n|:~B3 dBd|e/f/ge dBG|~B3 dBG|ABA AGA|B2B dBd|\nege dB/c/d|1 ~g3 aga|bgf g2A:|2 ~g3 ~a3|bge dBA||")
Note.create(tune_id: 2, user_id: 1, status:"public", key: "G", scale: "major", abc:"T: The Blarney Pilgrim\nR: jig\nM: 6/8\nL: 1/8\nK: Gmaj\n|:D3 DEG|A3 ABc|B3 AGE|GEA GE2|\nD3 DEG|A2A ABc|BG2 AGE|GED D3:|\n|:d3 dBG|A3 BGE|d3 dBG|AGA B3|\ng2e d2G|A3 B2d|dcB AGE|GED D3:|\n|:A2D B2D|A2D ABc|BAG AGE|GEA GED|\nADD BDD|ADD ABc|BAG AGE|GED D3:|")
Note.create(tune_id: 2, user_id: 2, status:"public", key: "D", scale: "mixolydian", abc:"T: The Blarney Pilgrim\nR: jig\nM: 6/8\nL: 1/8\nK: Dmix\n|:DED DEG|A2A ABc|BAG AGE|GEA GED|\nDED DEG|A2A ABc|BAG AGE|GED D3:|\nded dBG|AGA BGE|ded dBG|AGA GAB|\ng2e dBG|AGA BGE|B2G AGE|GED D3:|\nA2D B2D|A2D ABc|BAG AGE|GEA GED|\nADD BDD|ADD ABc|BAG AGE|GED D3:|")
Note.create(tune_id: 2, user_id: 3, status:"public", key: "E", scale: "mixolydian", abc:"T: The Blarney Pilgrim\nR: jig\nM: 6/8\nL: 1/8\nK: Emix\n|:E3 EFA|B3 Bcd|cBA BAF|AFB AFE|\nE3 EFA|B3 Bcd|cBA BAF|AFE E3:|\nefe ecA|BAB cAF|efe ecA|BAB Ace|\na2f ecA|BAB cAF|c2A BAF|AFE E3:|\nB2E c2E|B2E Bcd|cBA BAF|AFB AFE|\nBEE cEE|BEE Bcd|cBA BAF|AFE E3:|")
Note.create(tune_id: 3, user_id: 1, status:"draft", key: "E", scale: "major", abc:"T: Calliope House\nR: jig\nM: 6/8\nL: 1/8\nK: Emaj\nB|:eBB gBB|fBB gfe|cff f2e|fgf e2c|BcB B2G|\nB2c e2f|1 g2b gfe|f3 f2B:|2 gbg fed|e3 ega||\n|:b3 gbb|fbb gbb|a3 gag|f2e c2e|BcB B2G|\nB2c e2f|1 g2b gfe|f3 fga:|2 gbg fed|e3 e2||")
Note.create(tune_id: 3, user_id: 2, status:"public", key: "D", scale: "major", abc:"T: Calliope House\nR: jig\nM: 6/8\nL: 1/8\nK: Dmaj\n|:dAA fAA|eAA fAA|Bee e2d|efe dBA|FAA A2F|\nA2B d2e|1 f2f fed|e3 e2A:|2 f2f edc|d3 efg||\n|:a2a faa|eaa faa|g2g fgf|efe dBA|FAA A2F|\nA2B d2e|1 f2f fed|e3 efg:|2 f2f edc|d3 d3||")
Note.create(tune_id: 4, user_id: 4, status:"public", key: "E", scale: "dorian", abc:"T: The Swallowtail\nR: jig\nM: 6/8\nL: 1/8\nK: Edor\n|:F|GEE BEE|GEE BAG|FDD ADD|dcd AGF|\nGEE BEE|GEE B2c|dcd AGF|GEE 2E:|\nA|Bcd e2f|e2f edB|Bcd e2f|edB d2A|\nBcd e2f|e2f edB|dcd AGF|GEE 2E:|")
Note.create(tune_id: 4, user_id: 1, status:"public", key: "E", scale: "dorian", abc:"T: The Swallowtail\nR: jig\nM: 6/8\nL: 1/8\nK: Edor\n|:F|GEE BEE|GEE BAG|FDD ADD|dcd AGF|\nGEE BEE|GEE B2c|dcd AGF|GEE 2E:|\nA|Bcd e2f|e2f edB|Bcd e2f|edB d2A|\nBcd e2f|e2f edB|dcd AGF|GEE 2E:|")
Note.create(tune_id: 5, user_id: 3, status:"public", key: "A", scale: "major", abc:"T: Mouse In The Kitchen\nR: jig\nM: 6/8\nL: 1/8\nK: Amaj\n|:c2B cde|dcA ~F3|E2E EFA|B2A Bcd|\nc2B cde|dcA ~f3|a2e fec|1 BAG Acd:|2 BAG ~A3||\n|:B3 BAB|cec cBA|B2B BAB|cea aec|\n~B3 BAB|cec cBA|gae fec|1 BAG ~A3:|2 Bce fed||")
Note.create(tune_id: 5, user_id: 4, status:"public", key: "G", scale: "major", abc:"T: Mouse In The Kitchen\nR: jig\nM: 6/8\nL: 1/8\nK: Gmaj\n|:B3 Bcd|cBG E2G|D3 DEG|A3 AGA|\nB3 Bcd|cBG E2g|ged edB|1 ABd Gdc:|2 A3GcB||\n|:A3 AGE|B3 AGE|A3 AGA|Bdg zdB|\nA3 AGA|B3 AGE|ged edB|ABd GcB:|")
Note.create(tune_id: 6, user_id: 4, status:"public", key: "E", scale: "dorian", abc:"T: Morrison's\nR: jig\nM: 6/8\nL: 1/8\nK: Edor\n|:E3 B3|EBE AFD|EDE B3|dcB AFD|\nE3 B3|EBE AFD|G3 FGA|dAG FED:|\nBee fee|aee fee|Bee fee|a2g fed|\nBee fee|aee fee|gfe d2A|BAG FGA|\nBee fee|aee fee|Bee fee|faf def|\ng3 gfe|def g2d|edc d2A|BAG FED|")
Note.create(tune_id: 6, user_id: 2, status:"draft", key: "E", scale: "dorian", abc:": Morrison's\nR: jig\nM: 6/8\nL: 1/8\nK: Edor\n|:E3 B3|E3 AFD|EBE B2c|dcB AFD|\nE3 B3|E3 AFD|GBG FGA|dAG FED:|\nBee fee|aee fed|Bee fee|fag fed|\nBee fee|aee fef|gfe d2A|BAG FED|\nBee fee|aee fed|Bee fee|faf def|\ng3 gfe|def g2d|edc d2A|BAG FED|")
Note.create(tune_id: 6, user_id: 3, status:"public", key: "E", scale: "dorian", abc:"T: Morrison's\nR: jig\nM: 6/8\nL: 1/8\nK: Edor\n|:E3 B3|EBE AFD|E3 B3|dcB AFD|\nE3 BEB|E3 AFD|G3 FGA|dAG FED:|\nBee fee|aee fed|Bee fee|a2g fed|\nBee fee|aee fed|gfe d2A|BAG FGA|\nBee fee|aee fed|Bee fee|faf def|\ng3 gfe|def g2d|edc d2A|BAG FED|")
Note.create(tune_id: 6, user_id: 1, status:"public", key: "E", scale: "dorian", abc:"T: Morrison's\nR: jig\nM: 6/8\nL: 1/8\nK: Edor\n|:E2 E BEB|EBE AFD|EDE B3|dcB AFD|\nE3 B3|EBE AFD|G3 FGA|BAG FED:|\nBee fee|aee fed|Bee fee|fag fed|\nBee fee|aee fef|gfe d2A|BAG FED|\nBee fee|aee fed|Bee fee|faf def|\ng2g gfe|defg2d|edc d2A|BAG FED|")
Note.create(tune_id: 7, user_id: 2, status:"public", key: "D", scale: "major", abc:"T: Father O'Flynn\nR: jig\nM: 6/8\nL: 1/8\nK: Dmaj\n|:A|dAF DFA|ded cBA|dcd efg|fdf ecA|\ndAF DFA|ded cBA|dcd efg fdd d2:|\n|:g|fdf fga|ecA ABc|dcd Bed|cAA A2 =c|\nBGB Bcd|AFD DFA|dcd efg|fdd d2:|")
Note.create(tune_id: 7, user_id: 4, status:"public", key: "D", scale: "major", abc:"T: Father O'Flynn\nR: jig\nM: 6/8\nL: 1/8\nK: Dmaj\nA|dAF DFA|ded cBA|dcd ede|fdf ecA|dAF DFA|\nded cBA|dcd ede|fdd d3|(fg)f fga|ecA A3|dcd Bed|\ncAA A3|BGB Bcd|AFD DFA|dcd ede|fdd d2||")
Note.create(tune_id: 7, user_id: 1, status:"public", key: "G", scale: "major", abc:"T: Father O'Flynn\nR: jig\nM: 6/8\nL: 1/8\nK: Dmaj\n|:A|dAF DFA|ded cBA|dcd efg|fdf ecA|\ndAF DFA|ded cBA|dcd efg|fdc d2:|\n|:g|fdf fga|ecA ABc|dcd Bed|cAA A2c|\nBGB Bcd|AFD DFA|dcd efg|1 fdf e2:|2 fdc d2||")

Note.create(tune_id: 8, user_id: 2, status:"public", key: "E", scale: "dorian", abc:"T: A Fig For A Kiss\nR: slip jig\nM: 9/8\nL: 1/8\nK: Edor\nF|G2B E2B BAG|FGA D2A AGF|GAB E2B BAG|BdB AGF E2F|\nG2B e2B BAG|FGA D2A AGF|GAB E2B BAG|BdB AGF E2f||\ng2e g2e edB|f2d dcd fga|g2e g2e edB|dBG GBd e2f|\ng2e g2e edB|f2d dcd fga|gfe agf edc|BdB AGF E2||")
Note.create(tune_id: 8, user_id: 4, status:"public", key: "E", scale: "dorian", abc:"T: A Fig For A Kiss\nR: slip jig\nM: 9/8\nL: 1/8\nK: Edor\nG2B E2B BAG|F2A D2A AFD|G2B E2B BAG|B/c/dB AGF E2F|\nG2B E2B BAG|F2A D2A AFD|G2B E2B BAG|B/c/dB AGF E3||\ng2e g2e edB|f3 dfa afd|g2e g2e edB|AB/c/d efd e2f|\ng2e g2e edB|f3 dfa afd|gfe agf gfe|dcB AGF E3||")
Note.create(tune_id: 9, user_id: 1, status:"public", key: "E", scale: "minor", abc:"T: The Butterfly\nR: slip jig\nM: 9/8\nL: 1/8\nK: Emin\n|:B2E G2E F3|B2E G2E FED|B2E G2E F3|B2d d2B AFD:|\n|:B2d e2f g3|B2d g2e dBA|B2d e2f g2a|b2a g2e dBA:|\n|:B3 B2A G2A|B3 BAB dBA|B3 B2A G2A|B2d g2e dBA:|")
Note.create(tune_id: 9, user_id: 3, status:"public", key: "E", scale: "minor", abc:"T: The Butterfly\nR: slip jig\nM: 9/8\nL: 1/8\nK: Emin\n|:B2E G2E F3|B2E G2E FED|B2E G2E F3|B2d d2B AFD:|\n|:B2c e2f g3|B2c g2e dBA|B2c e2f g2a|b2a g2e dBA:|\n|:B3 B2A G2A|B3 BAB dBA|B3 B2A G2A|B2d g2e dBA:|")
Note.create(tune_id: 10, user_id: 1, status:"public", key: "E", scale: "minor", abc:"T: The Kid On The Mountain\nR: slip jig\nM: 9/8\nL: 1/8\nK: Emin\n|:EDE FEF G2 F|EDE BcA BGE|EDE FEF G2 G/A/|BAG FAG FED:|\n|:BGB AFA G2 D|GAB dge dBG|BGB AFA G2 G/A/|BAG FAG FED:|\n|:gfg eBe e2 f|gfg efg afd|gfg eBe e2 g/a/|bag fag fed:|\n|:eBB e2f gfg|eBB efg afd|eBB e2f g2 g/a/|bag fag fed:|\n|:edB dBA G2D|GAB dge dBd|edB dBA G2 G/A/|BAG FAG FED:|")
Note.create(tune_id: 10, user_id: 2, status:"public", key: "G", scale: "major", abc:"T: The Kid On The Mountain\nR: slip jig\nM: 9/8\nL: 1/8\nK: Gmaj\n|:EDE FEF G2F|E3B2A BGE|EDE FEF G2 A|BAG FAG FED:|\n|:BGB AFA G2 D|GAB dge dBA|BGB AFAG2A|BAG FAG FED:|\n|:gfg eBe e2f|gfg efg afd|gfg eBe ega|bag fag fed:|\n|:eBB e2 f g2 f|eBB efg afd|eBB e2 f g2 a|bag fag fed:|\n|:edB dBA G2 D|GAB dge dBd|edB dBA G2 A|BAG FAG FED:|")
Note.create(tune_id: 11, user_id: 3, status:"public", key: "D", scale: "major", abc:"T: The Foxhunter\nR: slip jig\nM: 9/8\nL: 1/8\nK: Dmaj\n|:FDF F2D G2E|FDF F2D E2D|FDF F2D G2B|AFD DEF E2D:|\n|:B3 BAG FGA|B2E E2F G2B|ABc dcB ABc|d2 D D2 F E2 D:|\n|:fdf f2d g2e|fdf f2d e2d|fdf f2d g2b|afd def e2d:|\n|:gfe dcB AGF|B2 E E2 F G2 B|ABc dcB ABc|d2 D DEF E2 D:|")
Note.create(tune_id: 11, user_id: 4, status:"public", key: "D", scale: "major", abc:"T: The Foxhunter\nR: slip jig\nM: 9/8\nL: 1/8\nK: Dmaj\nFGF FDFG2 E|FGF FDFE2 D|FGF FDFG2 B|AFD DEFE2 D:|\nBcB BAG FGA|B2 EE2F G2 B|ABc dcB ABc|d2 D DEFE2 D:|\nfgf fdf g2 e|fgf fdfe2 d|fgf fdfg2 b|afd def e2 d:|\ngfe dcB AGA|B2 EE2 FG2 B|ABc dcB ABc|d2 D DEF E2 D:|")

Note.create(tune_id: 12, user_id: 4, status:"public", key: "D", scale: "major", abc:"T: The Wise Maid\nR: reel\nM: 4/4\nL: 1/8\nK: Dmaj\n|:DE|F2FG FEDE|FAAB AFED|d2eg fdec|dBAG BEED|\nF2FG FEDE|FAAB AFED|d2eg fdec|dBAG FD:|\n|:FA|d2AG FDFA|dfaf gfeg|fedf eAcA|dfed cA A2|\nBAGB ADFD|dfaf gfed|Bdce dBAG|FGEF D2:|\n")
Note.create(tune_id: 13, user_id: 3, status:"public", key: "G", scale: "major", abc:"T: Christmas Eve\nR: reel\nM: 4/4\nL: 1/8\nK: Gmaj\n|:GE|D3E ~G3A|B2dB ABGA|BAGE DB,DE|GABG ABGE|\nDB,DE ~G3A|B2dB ABGA|BAAB GE~E2|ABGE G2:|\n|:GA|BA (3Bcd edeg|abge g2eg|a2ge ~g3e|dedB ABGA|\nBA (3Bcd edeg|abge g2eg|abge d2BG|ABGE G2:|\n|:dc|BG~G2 dG (3Bcd|eg~g2 egdc|BG~G2 DGBG|EAAG EAAc|\nBG~G2 dG (3Bcd|eg~g2 egdg|bgag eddB|ABGE G2:|")
Note.create(tune_id: 14, user_id: 1, status:"public", key: "A", scale: "dorian", abc:"T: The Congress\nR: reel\nM: 4/4\nL: 1/8\nK: Ador\n|:eAAG A2 B/c/d|eaaf gedg|eAA2 eAcA|BGGF GABd|\neAAG A2 B/c/d|eaaf gedB|cBcd eged|cABG A2 B/c/d:|\n|:eaag a3g|eaaf gedg|egdg egdg|eaaf gedg|\neaag a3g|eaaf gedB|cBcd eged|cABG A2 B/c/d:|")
Note.create(tune_id: 14, user_id: 4, status:"public", key: "A", scale: "dorian", abc:"T: The Congress\nR: reel\nM: 4/4\nL: 1/8\nK: Ador\n|:eAAG A2 B/c/d|eaaf gedg|eAA2 eAcA|BGGF GABd|\neAAG A2 B/c/d|eaaf gedB|cBcd eged|cABG A2 B/c/d:|\n|:eaag a3g|eaaf gedg|egdg egdg|eaaf gedg|\neaag a3g|eaaf gedB|cBcd eged|cABG A2 B/c/d:|")
Note.create(tune_id: 15, user_id: 2, status:"public", key: "E", scale: "dorian", abc:"T: Drowsy Maggie\nR: reel\nM: 4/4\nL: 1/8\nK: Edor\n|:E2BE dEBE|E2BE AFDF|E2BE dEBE|BABc dAFD:|\nd2fd c2ec|defg afge|d2fd c2ec|BABc dAFA|\nd2fd c2ec|defg afge|afge fdec|BABc dAFD|")
Note.create(tune_id: 15, user_id: 3, status:"public", key: "E", scale: "dorian", abc:"T: Drowsy Maggie\nR: reel\nM: 4/4\nL: 1/8\nK: Edor\n|:E2BE dEBE|E2BE AFDF|E2BE dEBE|BABc dAFD:|\nd2fd cdec|defg afge|d2fd cdec|BABc dAFA|\nd2fd c2ec|defg afga|bgaf gfed|BABc dAFD|")
Note.create(tune_id: 15, user_id: 4, status:"public", key: "E", scale: "dorian", abc:"T: Drowsy Maggie\nR: reel\nM: 4/4\nL: 1/8\nK: Edor\n|:E2BE dEBE|E2BE AFDF|E2BE dEBE|B2Bc dAFD:|\ndefd cdec|defg afge|d2fd cdec|B2Bc dAFA|\ndefd cdec|defg a2eg|afge fdec|dBAG FDED|")
Note.create(tune_id: 16, user_id: 1, status:"public", key: "D", scale: "major", abc:"T: The Wind That Shakes The Barley\nR: reel\nM: 4/4\nL: 1/8\nK: Dmaj\nA2AB AFED|B2BA BcdB|A2AB AFED|gfed BcdB|\nA2AB AFED|B2BA BcdB|A2AB AFED|gfed Bcde||\nf2fd g2ge|f2fd Bcde|f2fd g2fg|afed Bcde|\nf2fd g2ge|f2fd Bcde|defg a2ab|afed BcdB||")
Note.create(tune_id: 16, user_id: 3, status:"public", key: "D", scale: "major", abc:"T: The Wind That Shakes The Barley\nR: reel\nM: 4/4\nL: 1/8\nK: Dmaj\nA2AB AFED|B2BA BcdB|A2AB ABde|1 fedc BcdB:|2 fedc Bcde||\nf2fd g2ge|f2fd Bcde|f2fd g2fg|afed Bcde|\nf2fd g2ge|f2fd Bcde|defg a2ab|afed BcdB||")
Note.create(tune_id: 16, user_id: 4, status:"public", key: "D", scale: "major", abc:"T: The Wind That Shakes The Barley\nR: reel\nM: 4/4\nL: 1/8\nK: Dmaj\nA2AB AFED|B2BA Bcd2|A2AB AFED|gfed BcdB|\nA2AB AFED|B2BA BcdB|A2AB AFED|gfed Bcde||\nf2fd g2ge|f2fd edBd|f2fd g2ab|afed Bcde|\nf2fd g2ge|f2fd edBd|defg afbf|gfed BcdB||")
Note.create(tune_id: 17, user_id: 2, status:"public", key: "A", scale: "dorian", abc:"T: The Gravel Walks\nR: reel\nM: 4/4\nL: 1/8\nK: Ador\n|:'Am'A2 eA (3cBA eA|A2 eA 'G'BAGB|'Am'A2 eA (3Bcd ef|'G'gedc BAGB:|\n'Am'A2 aA gAfA|A2 eA 'G'BAGB|'Am'A2 aA gAfA|'G'gedc BAGB|\n'Am'A2 aA gAfA|A2 eA 'G'BAGB|'Am'ABcd efga|'G'gedc BAGB|\n|:'Am'(3cBA BG A2 AB|cAAd 'G'BAGB|'Am'(3cBA BG ABcd|'G'efge dBGB:|\nK:Cmaj\n|:'C'c2 gc acgc|c2 gc 'G'BAGB|'C'c2 gc acga|'G'gedc BAGB|\n'C'c2 gc acgc|c2 gc 'G'BAGB|'Am'ABcd efga|'G'gedc BAGB:| ")
Note.create(tune_id: 18, user_id: 3, status:"public", key: "D", scale: "major", abc:"T: The Silver Spear\nR: reel\nM: 4/4\nL: 1/8\nK: Dmaj\nAG|:FA ~A2 BAFA|dfed BcdA|FA ~A2 BAFA|dfed ~B3 A|\nFA ~A2 BAFA|dfed Bdef|~g3 e ~f3 e|1 dfed ~B2 A2:|2 dfed Bcde||\n|:f2 af bfaf|gfed Bcde|f2 af bfaf|gfed ~B2 A2|\nf2 af bfaf|gfed Bdef|~g3 e ~f3 e|1 dfed ~B2 A2:|2 dfed ~B2|| ")
Note.create(tune_id: 18, user_id: 2, status:"public", key: "D", scale: "major", abc:"T: The Silver Spear\nR: reel\nM: 4/4\nL: 1/8\nK: Dmaj\nAG|:FA ~A2 BAFA|dfed BcdA|FA ~A2 BA (3FGA|dfed Bcd2|\nFA ~A2 BA (3FGA|dfed Bdef|~g3 e ~f3 e|1 dfed ~B2 A2:|2 dfed Bcde||\n|:f~a3 bfaf|defd edBd|f~a3 bfaf|defd ~B2 A2|\nf~a3 bfaf|defd edef|~g3 e ~f3 e|1 dfed ~B2 A2:|2 dfed edBA|| ")
Note.create(tune_id: 19, user_id: 4, status:"public", key: "E", scale: "dorian", abc:"T: Toss The Feathers\nR: reel\nM: 4/4\nL: 1/8\nK: Edor\n|:EBBB dBBB|EBBB FDFA|BE E2 BABc|defe dBAF:|\nBeed e2 de|fede fe e2|febe febe|fede fee2|\nBeed e2 de|fede fa a2|b2bf a2af|defe dBAF| ")
Note.create(tune_id: 19, user_id: 1, status:"public", key: "E", scale: "doriann", abc:"T: Toss The Feathers\nR: reel\nM: 4/4\nL: 1/8\nK: Edor\nEBBB dBBB|EBBA FEFA|BE E2 BABc|1 d2 fe dBAF:|2 d2 fe dBAd||\nBeed e2 de|fede fe e2|febe febe|fede fe e2|\nBeed e2 de|fede fgaf|b2 bg a2 af|egfe dBAF|| ")
Note.create(tune_id: 20, user_id: 2, status:"public", key: "D", scale: "mixolydian", abc:"T: Toss The Feathers\nR: reel\nM: 4/4\nL: 1/8\nK: Dmix\nD2 (3FED AD (3FED|ABcA GE~E2|D2 (3FED ADFA|dfed cAGE|\nD2 (3FED AD (3FED|ABcA GE~E2|cABG A2B^c|dfed cAGE:|\n|:Ad~d2 Ad~d2|Ad^cd edcd|eaag ~a3g|eaag ed^cd|\nefge afge|dfed cAAB|cABG A2B^c|dfed cAGE:| ")
Note.create(tune_id: 20, user_id: 3, status:"public", key: "D", scale: "mixolydian", abc:"T: Toss The Feathers\nR: reel\nM: 4/4\nL: 1/8\nK: Dmix\n|:D2 ED ADED|ABcA GEDE|D2 F/E/D ADED|AddB cAGE\nD2 DA D2 ED|ABcA GE E2|cABG A2 AB|1 cded cAGE:|\nAd d2 ad d2|Ad d2 ed^cd|eaag a2 ge|a2 ag aged\nefge a2 fg|efed dcAB|cABG A2 AB|1 cded cAGB:| ")

Note.create(tune_id: 21, user_id: 3, status:"public", key: "D", scale: "major", abc:"T: The Belfast\nR: hornpipe\nM: 4/4\nL: 1/8\nK: Dmaj\nag|:f/a/f df AdFA|DFAd f/g/f ef|gbeg ceAF|GABG E2 ag|\nf/a/f df AdFA|DFAd f/g/f ef|gfed cABc|1 d2 f2 d2 ag:|2 d2 f2 d2 D/E/F||\nGFGA Bcde|fgfe dcdB|A2f2 fe f2|G2 e2 ed eF|\nGFGA Bcde|fgfe dcdB|Afed cABc|1 d2 f2 d2 D/E/F:|2 d2 f2 d2 ag||\nf/g/f e/f/e d/e/d c/d/c|B/c/B A/B/A G2 ba|g/a/g f/g/f e/f/e d/e/d|c/d/c B/c/B A2 ag|\nf/g/f e/f/e d/e/d c/d/c|B/c/B A/B/A G/A/G F/G/F|Eged cA A/B/c|d2 f2 d2 ag:| ")
Note.create(tune_id: 21, user_id: 2, status:"public", key: "D", scale: "major", abc:"T: The Belfast\nR: hornpipe\nM: 4/4\nL: 1/8\nK: Dmaj\n|:ag|fadf AdAF|DFAd f2ef|gbeg BeAF|GABG E2ag|\nfadf AdAF|DFAd f2ef|gfed cABc|d2f2 d2:|\n|:(3DEF|GFGA Bcde|fgfe dcdB|A2f2 fef2|G2e2 ede2|\nGFGA Bcde|fgfe dcdB|Afed cABc|d2f2 d2:|\n|:a>g|(3fgf (3efe (3ded (3cdc|(3BcB (3ABA G2 b>a|(3gag (3fgf (3efe (3ded|(3cdc (3BcB A2 a>g|\n(3fgf (3efe (3ded (3cdc|(3BcB (3ABA (3GAG (3FGF|E>ge>d c>AB>c|d2 f2 d2:| ")
Note.create(tune_id: 22, user_id: 2, status:"public", key: "G", scale: "major", abc:"T: Cronin's\nR: hornpipe\nM: 4/4\nL: 1/8\nK: Gmaj\n|:BA|GABd dBde|gage dega|bage dBGA|BAAG AcBA|\nGABd dBde|gage dega|bage dBAc|AGGF G2:|\n|:(3efg|afd^c d2ga|beed e2ga|bg (3agf gedB|BAAG AcBA|\nGABd dBde|gage dega|bage dBAB|G2 GF G2:| ")
Note.create(tune_id: 22, user_id: 4, status:"public", key: "G", scale: "major", abc:"T: Cronin's\nR: hornpipe\nM: 4/4\nL: 1/8\nK: Gmaj\n|:BA|GABd dBde|gage dega|bage dBGA|BAAG AcBA|\nGABd dBde|gage dega|bage dBAB|G2 GF G2:|\n|:fg|add^c d2ga|beed e2ga|bgaf (3gfe dB|BAAG AcBA|\nGABd dBde|gage dega|bage dBAB|G2 GF G2:| ")
Note.create(tune_id: 23, user_id: 2, status:"public", key: "E", scale: "minor", abc:"T: The Rights Of Man\nR: hornpipe\nM: 4/4\nL: 1/8\nK: Emin\n|:GA|B2A2 G2F2|EFGA B2ef|gfed edBd|cBAG A2GA|\nBcAB GAFG|EFGA B2ef|gfed Bgfg|e2 E2 E2:|\n|:ga|babg efga|babg egfe|d^cde fefg|afdf a2gf|\nedef gfga|bgaf gfef|gfed Bgfg|e2 E2 E2:| ")
Note.create(tune_id: 23, user_id: 4, status:"public", key: "E", scale: "minor", abc:"T: The Rights Of ManR: hornpipe\nM: 4/4\nL: 1/8\nK: Emin\n|:GA|BdAB GAGF|EFGA B2 ef|gfed edBd|cBAG A2 GA|\nBdAB GAGF|EFGA B2 ef|gfed Bgfg|e2 E2 E2:|\n|:ga|bagf efge|Begf afge|dcde defg|agaf bagf|\nedef gfga|bBaB gBfB|gfed Bgfg|e2 E2 E2:| ")
Note.create(tune_id: 24, user_id: 1, status:"public", key: "G", scale: "major", abc:"T: Off To California\nR: hornpipe\nM: 4/4\nL: 1/8\nK: Gmaj\n(3DEF|:GFGB AGED|GBdg e2 (3def|gfgd edBG|ABAG E2 (3DEF|\nGFGB AGED|GBdg e2 (3def|gfgd edBG|1 (3ABA GF G2 (3DEF:|2 (3ABA GF G2 (3def||\n|:gfeg fedf|edef edBd|gfgd edBG|ABAG E2 (3DEF|\nGFGB AGED|GBdg e2 (3def|gfgd edBG|1 (3ABA GF G2 (3def:|2 (3ABA GF G4|| ")

Note.create(tune_id: 25, user_id: 1, status:"public", key: "D", scale: "major", abc:"T: John Ryan's\nR: polka\nM: 2/4\nL: 1/8\nK: Dmaj\n|:dd B/c/d/B/|AF AF|dd B/c/d/B/|AF ED|\ndd B/c/d/B/|AF Ad/e/|fd ec|1 d2 d2:|2 df dd/e/||\n|:fd de/f/|gf ed/e/|fd de|fd/f/ a>g|\nfd de/f/|gf ed/e/|fd ec|1 df dd/e/:|2 d2 d2|| ")
Note.create(tune_id: 25, user_id: 3, status:"public", key: "D", scale: "major", abc:"T: John Ryan's\nR: polka\nM: 2/4\nL: 1/8\nK: Dmaj\ndd B/c/d/B/|AF ED|dd B/c/d/B/|AF E2|\ndd B/c/d/B/|AF Ad|fd ec|d2 d2||\nfd de/f/|gf ed|fd de/f/|gf a2|")
Note.create(tune_id: 26, user_id: 1, status:"public", key: "D", scale: "major", abc:"T: Egan's\nR: polka\nM: 2/4\nL: 1/8\nK: Dmaj\n|:fA BA|fA BA|d2 e>f|ed BA|fA BA|fA BA|d2 e>f|ed d2:|\n|:fa f>e|ed BA|d2 e>f|ed BA|fa f>e|ed BA|d2 e>f|ed d2:| ")
Note.create(tune_id: 27, user_id: 3, status:"public", key: "A", scale: "major", abc:"T: Bill Sullivan's\nR: polka\nM: 2/4\nL: 1/8\nK: Amaj\n|:a2 a>f|ec a>f|ce a>f|ec BA|\na2 a>f|ec a>f|ce Bc|BA A2:|\n|:ce ed/c/|df fe/d|ce eA/B/|cB BA/B/|\nce ed/c|df fe/d/|ce B>c|BA A2:| ")
Note.create(tune_id: 27, user_id: 1, status:"public", key: "A", scale: "major", abc:"T: Bill Sullivan's\nR: polka\nM: 2/4\nL: 1/8\nK: Amaj\n|:a2 a>f|ec a>f|ec a>f|ec BA|\na2 a>f|ec a2|ce B>c|BA A2:|\n|:ce ec|df fA|ce eA|cB AB|\nce eA|df f2|ce B>c|BA A2:| ")
Note.create(tune_id: 28, user_id: 4, status:"public", key: "D", scale: "mixolydian", abc:"T: Tom Sullivan's\nR: polka\nM: 2/4\nL: 1/8\nK: Dmix\nD/E/F/G/ AB|cA AG|Ad dc|d2 d>e|\nfd ed|cA A>B|cA GE|D2 D2:|\nfd ed|cA Ad/e/|fd ef|g2 a>g|\nfd ed|cA A>B|cA GE|D2 D2:| ")
Note.create(tune_id: 28, user_id: 2, status:"public", key: "D", scale: "mixolydian", abc:"T: Tom Sullivan's\nR: polka\nM: 2/4\nL: 1/8\nK: Dmix\n|:D/E/F/G/ AB|c/B/A AG|Ad d^c|d2 de|\nfd ed|cA AB|c/B/A GE|1 D2 D2:|2 D2 De||\n|:fd ed|c/B/A Ad/e/|fd ef|g2 a>g|\nfd ed|c/B/A AB|cA G/F/E|1 D2 De:|2 D2 D2|| ")

Note.create(tune_id: 29, user_id: 2, status:"public", key: "G", scale: "major", abc:"T: Fanny Power\nR: waltz\nM: 3/4\nL: 1/8\nK: Gmaj\nD2|:G4 D2|G3A B2|c4 B2|A4 G2|G2 F2 E2|D2 F2 D2|F4 G2|A4 c2|\nB3A G2|B2 c2 d2|e4 A2|A3B G2|G2 F2 E2|D2 G2 F2|G6|1 G4 D2:|2 G4 d2||\n|:d2 Bc d2|d2 Bc d2|G3B G2|G2 B2 d2|e2 cd e2|e2 cd e2|A3c A2|A2 c2 A2|\nB3c d2|e2 f2 g2|f3g a2|d4 c2|B3A G2|D2 G2 F2|G6|1 G4 d2:|2 G6|| ")
Note.create(tune_id: 29, user_id: 3, status:"public", key: "G", scale: "major", abc:"T: Fanny Power\nR: waltz\nM: 3/4\nL: 1/8\nK: Gmaj\n|:D|G2D G>AB|c2B A2G|F>GE D>ED|F2G A>Bc|\nB>AG B>cd|e2A A2G|F>GE D>GF|G3 G2:|\n|:d|dB/c/d dB/c/d|G>AG GBd|ec/d/e ec/d/e|A>BA ABc|\nB>cd e>fg|f>ga d2c|B>AG A/B/cF|G3 G2:| ")
Note.create(tune_id: 30, user_id: 1, status:"public", key: "D", scale: "major", abc:"T: Sí Beag Sí Mór\nR: waltz\nM: 3/4\nL: 1/8\nK: Dmaj\nAde|:f2 fe d2|d3 e d2|B4 A2|F3G A2|BA Bc d2|e3 ade|f4 e2|\nd4 fd|B4 ec|A4 dA|F4 E2|D4 FD|B4 ec|A3 edc|d2 dc de|d3 ade:|\n|:f2 fe d2|ed ef a2|b4 a2|f4 ed|e4 a2|f4 ed|d4 B2|B4 A2|\nF4 E2|D4 fd|B4 ec|A4 fa|ba gf ed|e4 dc|d2 de fe|1 d3 Ade:|2 d3|| ")
Note.create(tune_id: 30, user_id: 4, status:"public", key: "D", scale: "major", abc:"T: Sí Beag Sí Mór\nR: waltz\nM: 3/4\nL: 1/8\nK: Dmaj\nde|:f3e d2|d2 de d2|B4 A2|F4 A2|BA Bc d2|e4 de|f2 f2 e2|\nd4 f2|B4 e2|A4 d2|F4 E2|D4 e2|B4 e2|A4 dc|d6|d4 de:|\n|:f2 fe d2|ed ef a2|b4 a2|f4 ed|e4 a2|f4 e2|d4 B2|A4 BA|\nF4 E2|D4 f2|B4 e2|A4 a2|ba gf ed|e4 dc|d6|1 d4 de:|2 d6|| ")
Note.create(tune_id: 31, user_id: 4, status:"public", key: "G", scale: "major", abc:"T: Planxty Irwin\nR: waltz\nM: 3/4\nL: 1/8\nK: Gmaj\nd2|:g4 f2|e3f g2|d4 c2|B3A G2|c4 A2|B3c d2|1 F4 G2|A4 d2:|2 G4 F2|G4 d2||\n|:g4 g2|g3f g2|a2b a2|a2 f2 d2|b4 b2|a3b g2|f3g e2|d3e f2|\ng4 f2|e3f g2|d4 c2|B3A G2|c4 A2|B3c d2|G4 F2|1 G4 d2:|2 G6|| ")
Note.create(tune_id: 32, user_id: 3, status:"public", key: "G", scale: "major", abc:"T: The South Wind\nR: waltz\nM: 3/4\nL: 1/8\nK: Gmaj\nc2|B3A G2|B3c d2|A4 B2|A4 c2|B3A G2|E3D E2|G4 G2|1 G4:|2 G4 d2||\ng4 g2|g3f e2|d4 e2|d4 c2|B3A G2|B3c d2|A4 B2|A4 d2|\ng4 g2|g3f e2|d4 e2|d4 c2|B3A G2|Ac3 F2|G4 G2|G4|| ")

Note.create(tune_id: 33, user_id: 3, status:"public", key: "G", scale: "major", abc:"T: Down By The Sally Gardens\nR: air\nM: 4/4\nL: 1/8\nK: Gmaj\nGA|B2AG A2 Bd|e4 d2 gd|e2 dB A3 G|G4 z2GA|\nB2 AG A2 Bd|e4 d2 gd|e2 dB A3G|G4 z2 d2||\ng2 fd e2 fg|f3 e d2 Bd|e2 dB dega|g4 z2 GA|\nB2 AG A2 Bd|e4 d2 gd|e2 dB A3G|G4 z2|| ")
Note.create(tune_id: 33, user_id: 1, status:"public", key: "D", scale: "major", abc:"T: Down By The Sally Gardens\nR: air\nM: 4/4\nL: 1/8\nK: Dmaj\nDE|F2ED E2 FA|B4 A2 dA|B2 AF E3 D|D4 z2DE|\nF2 ED E2 FA|B4 A2 dA|B2 AF E3D|D4 z2 A2||\nd2 cA B2 cd|c3 B A2 FA|B2 AF ABde|d4 z2 DE|\nF2 ED E2 FA|B4 A2 dA|B2 AF E3D|D4 z2|| ")