# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
require 'time'

Tune.create(name: "The Kesh", rhythm: "Jig", alt_name: "Castel, Kincora")
Tune.create(name: "Blarney Pilgrim", rhythm: "Jig")
Tune.create(name: "Calliope House", rhythm: "Jig")
Tune.create(name: "Swallowtail", rhythm: "Jig")
Tune.create(name: "Mouse In The Kitchen", rhythm: "Jig")
Tune.create(name: "Morrison's", rhythm: "Jig")
Tune.create(name: "Father O'Flynn", rhythm: "Jig")

Tune.create(name: "A Fig For A Kiss", rhythm: "Slip Jig")
Tune.create(name: "Butterfly", rhythm: "Slip Jig")
Tune.create(name: "Kid on The Mountain", rhythm: "Slip Jig")
Tune.create(name: "Foxhunter's", rhythm: "Slip Jig")

Tune.create(name: "Wise Maid", rhythm: "Reel")
Tune.create(name: "Christmas Eve", rhythm: "Reel")
Tune.create(name: "Congress", rhythm: "Reel")
Tune.create(name: "Drowsy Maggie", rhythm: "Reel")
Tune.create(name: "Wind That Shakes The Barley", rhythm: "Reel")
Tune.create(name: "Gravel Walk", rhythm: "Reel")
Tune.create(name: "Sliver Spear", rhythm: "Reel")
Tune.create(name: "Toss The Feather", rhythm: "Reel")
Tune.create(name: "Toss The Feather", rhythm: "Reel")

Tune.create(name: "Belfast", rhythm: "Hornpipe")
Tune.create(name: "Cronin's", rhythm: "Hornpipe")
Tune.create(name: "Rights Of Man", rhythm: "Hornpipe")
Tune.create(name: "Off To California", rhythm: "Hornpipe")

Tune.create(name: "John Ryan", rhythm: "Polka")
Tune.create(name: "Egan's", rhythm: "Polka")
Tune.create(name: "Ballydesmond No.1", rhythm: "Polka")
Tune.create(name: "Ballydesmond No.2", rhythm: "Polka")
Tune.create(name: "Ballydesmond No.3", rhythm: "Polka")
Tune.create(name: "Bill Sullivan's", rhythm: "Polka")
Tune.create(name: "Finnish", rhythm: "Polka")
Tune.create(name: "Tom Sullivan's", rhythm: "Polka")

Tune.create(name: "Fanny Power", rhythm: "O'Carolan's")
Tune.create(name: "Si beag Si mor", rhythm: "O'Carolan's")
Tune.create(name: "Planxty Hewlett", rhythm: "O'Carolan's")
Tune.create(name: "0'Carolan's Draught", rhythm: "O'Carolan's")

Tune.create(name: "South Wind", rhythm: "Waltz")
Tune.create(name: "Inisheer", rhythm: "Waltz")

Tune.create(name: "Down By The Sally Garden", rhythm: "Air")

User.create(name: "関西アイリッシュセッション", pref: "大阪", date: "第3土曜日　21時〜", login_id: "ksis", password: "kansaiyd", password_confirmation: "kansaiyd")
User.create(name: "関東アイルランド音楽セッション会", pref: "東京", date: "毎週水曜日の夜(時間不定)", login_id: "eims", password: "kantou23", password_confirmation: "kantou23")
User.create(name: "南日本アイルランド音楽会", pref: "九州", date: "月1回", login_id: "sjim", password: "enjoy", password_confirmation: "enjoy")
User.create(name: "アイル・セッション・イン・北日本", pref: "北海道", date: "不定期", login_id: "iinn", password: "hokuai", password_confirmation: "hokuai")
User.create(name: "ゲスト", pref:"未定", date: "不定期", login_id: "guest", password: "guest", password_confirmation: "guest")

Note.create(tune_id: 1, user_id: 1, status:"public", key: "G", scale: "major", abc:"T: The Kesh\nR: jig\nM: 6/8\nL: 1/8\nK: Gmaj\n|:G3 GAB|A3 ABd|edd gdd|edB dBA|\nGAG GAB|ABA ABd|edd gdd|BAF G3:|\n|:B2B d2d|ege dBA|B2B dBG|ABA AGA|\nBAB d^cd|ege dBd|gfg aga|bgg g3:|")
Note.create(tune_id: 1, user_id: 3, status:"draft", key: "A", scale: "major", abc:"T: The Kesh\nR: jig\nM: 6/8\nL: 1/8\nK: Gmaj\n|:G2D GAB|A2G ABd|ede gdB|B2G G2D|\nG2D GAB|A2G ABd|ede gdB|B2A G3:|\n|:Bgg dgg|Bgg dgg|Bgg dgg|B2G AGE|\nBgg dgg|~g2e d3|g3 a3|1 bgg g3:|2 bgg B2A||")
Note.create(tune_id: 1, user_id: 4, status:"draft", key: "D", scale: "major", abc:"T: The Kesh\nR: jig\nM: 6/8\nL: 1/8\nK: Dmaj\nA,|:D3 DEF|E3 EFA|BAA dAA|BAF AFE|\nD3 DEF|E3 EFA|BAA dAF|EDC D3:|\n|:{E}F3 AFA|BdB BAF|{E}F3 AFD|EFE EDE|\n{E}F3 AFA|BdB B2B| dcd ede|fdc d3:|")
Note.create(tune_id: 1, user_id: 2, status:"public", key: "D", scale: "major", abc:"T: The Kesh\nR: jig\nM: 6/8\nL: 1/8\nK: Gmaj\nD|:~G3 GAB|~A3 AB/c/d|edd gdd|edB dBA|\n~G3 GAB|~A3 ABd|edd gdB|1 AGF G2D:|2 AGF G2A||\n|:~B3 dBd|e/f/ge dBG|~B3 dBG|ABA AGA|B2B dBd|\nege dB/c/d|1 ~g3 aga|bgf g2A:|2 ~g3 ~a3|bge dBA||")
Note.create(tune_id: 2, user_id: 1, status:"public", key: "G", scale: "major", abc:"T: The Blarney Pilgrim\nR: jig\nM: 6/8\nL: 1/8\nK: Gmaj\n|:D3 DEG|A3 ABc|B3 AGE|GEA GE2|\nD3 DEG|A2A ABc|BG2 AGE|GED D3:|\n|:d3 dBG|A3 BGE|d3 dBG|AGA B3|\ng2e d2G|A3 B2d|dcB AGE|GED D3:|\n|:A2D B2D|A2D ABc|BAG AGE|GEA GED|\nADD BDD|ADD ABc|BAG AGE|GED D3:|")
Note.create(tune_id: 2, user_id: 2, status:"public", key: "D", scale: "mixolydian", abc:"T: The Blarney Pilgrim\nR: jig\nM: 6/8\nL: 1/8\nK: Dmix\n|:DED DEG|A2A ABc|BAG AGE|GEA GED|\nDED DEG|A2A ABc|BAG AGE|GED D3:|\nded dBG|AGA BGE|ded dBG|AGA GAB|\ng2e dBG|AGA BGE|B2G AGE|GED D3:|\nA2D B2D|A2D ABc|BAG AGE|GEA GED|\nADD BDD|ADD ABc|BAG AGE|GED D3:|")
Note.create(tune_id: 2, user_id: 3, status:"public", key: "E", scale: "mixolydian", abc:"T: The Blarney Pilgrim\nR: jig\nM: 6/8\nL: 1/8\nK: Emix\n|:E3 EFA|B3 Bcd|cBA BAF|AFB AFE|\nE3 EFA|B3 Bcd|cBA BAF|AFE E3:|\nefe ecA|BAB cAF|efe ecA|BAB Ace|\na2f ecA|BAB cAF|c2A BAF|AFE E3:|\nB2E c2E|B2E Bcd|cBA BAF|AFB AFE|\nBEE cEE|BEE Bcd|cBA BAF|AFE E3:|")
Note.create(tune_id: 3, user_id: 1, status:"draft", key: "E", scale: "major", abc:"T: Calliope House\nR: jig\nM: 6/8\nL: 1/8\nK: Emaj\nB|:eBB gBB|fBB gfe|cff f2e|fgf e2c|BcB B2G|\nB2c e2f|1 g2b gfe|f3 f2B:|2 gbg fed|e3 ega||\n|:b3 gbb|fbb gbb|a3 gag|f2e c2e|BcB B2G|\nB2c e2f|1 g2b gfe|f3 fga:|2 gbg fed|e3 e2||")
Note.create(tune_id: 3, user_id: 2, status:"public", key: "D", scale: "major", abc:"T: Calliope House\nR: jig\nM: 6/8\nL: 1/8\nK: Dmaj\n|:dAA fAA|eAA fAA|Bee e2d|efe dBA|FAA A2F|\nA2B d2e|1 f2f fed|e3 e2A:|2 f2f edc|d3 efg||\n|:a2a faa|eaa faa|g2g fgf|efe dBA|FAA A2F|\nA2B d2e|1 f2f fed|e3 efg:|2 f2f edc|d3 d3||")
Note.create(tune_id: 4, user_id: 4, status:"public", key: "E", scale: "dorian", abc:"T: The Swallowtail\nR: jig\nM: 6/8\nL: 1/8\nK: Edor\n|:F|GEE BEE|GEE BAG|FDD ADD|dcd AGF|\nGEE BEE|GEE B2c|dcd AGF|GEE 2E:|\nA|Bcd e2f|e2f edB|Bcd e2f|edB d2A|\nBcd e2f|e2f edB|dcd AGF|GEE 2E:|")
Note.create(tune_id: 4, user_id: 1, status:"public", key: "E", scale: "dorian", abc:"T: The Swallowtail\nR: jig\nM: 6/8\nL: 1/8\nK: Edor\n|:F|GEE BEE|GEE BAG|FDD ADD|dcd AGF|\nGEE BEE|GEE B2c|dcd AGF|GEE 2E:|\nA|Bcd e2f|e2f edB|Bcd e2f|edB d2A|\nBcd e2f|e2f edB|dcd AGF|GEE 2E:|")
Note.create(tune_id: 5, user_id: 3, status:"public", key: "A", scale: "major", abc:"T: Mouse In The Kitchen\nR: jig\nM: 6/8\nL: 1/8\nK: Amaj\n|:c2B cde|dcA ~F3|E2E EFA|B2A Bcd|\nc2B cde|dcA ~f3|a2e fec|1 BAG Acd:|2 BAG ~A3||\n|:B3 BAB|cec cBA|B2B BAB|cea aec|\n~B3 BAB|cec cBA|gae fec|1 BAG ~A3:|2 Bce fed||")
Note.create(tune_id: 5, user_id: 4, status:"public", key: "G", scale: "major", abc:"T: Mouse In The Kitchen\nR: jig\nM: 6/8\nL: 1/8\nK: Gmaj\n|:B3 Bcd|cBG E2G|D3 DEG|A3 AGA|\nB3 Bcd|cBG E2g|ged edB|1 ABd Gdc:|2 A3GcB||\n|:A3 AGE|B3 AGE|A3 AGA|Bdg zdB|\nA3 AGA|B3 AGE|ged edB|ABd GcB:|")
Note.create(tune_id: 6, user_id: 4, status:"public", key: "E", scale: "dorian", abc:"T: Morrison's\nR: jig\nM: 6/8\nL: 1/8\nK: Edor\n|:E3 B3|EBE AFD|EDE B3|dcB AFD|\nE3 B3|EBE AFD|G3 FGA|dAG FED:|\nBee fee|aee fee|Bee fee|a2g fed|\nBee fee|aee fee|gfe d2A|BAG FGA|\nBee fee|aee fee|Bee fee|faf def|\ng3 gfe|def g2d|edc d2A|BAG FED|")
Note.create(tune_id: 6, user_id: 2, status:"draft", key: "E", scale: "dorian", abc:": Morrison's\nR: jig\nM: 6/8\nL: 1/8\nK: Edor\n|:E3 B3|E3 AFD|EBE B2c|dcB AFD|\nE3 B3|E3 AFD|GBG FGA|dAG FED:|\nBee fee|aee fed|Bee fee|fag fed|\nBee fee|aee fef|gfe d2A|BAG FED|\nBee fee|aee fed|Bee fee|faf def|\ng3 gfe|def g2d|edc d2A|BAG FED|")
Note.create(tune_id: 6, user_id: 3, status:"public", key: "E", scale: "dorian", abc:"T: Morrison's\nR: jig\nM: 6/8\nL: 1/8\nK: Edor\n|:E3 B3|EBE AFD|E3 B3|dcB AFD|\nE3 BEB|E3 AFD|G3 FGA|dAG FED:|\nBee fee|aee fed|Bee fee|a2g fed|\nBee fee|aee fed|gfe d2A|BAG FGA|\nBee fee|aee fed|Bee fee|faf def|\ng3 gfe|def g2d|edc d2A|BAG FED|")
Note.create(tune_id: 6, user_id: 1, status:"public", key: "E", scale: "dorian", abc:"T: Morrison's\nR: jig\nM: 6/8\nL: 1/8\nK: Edor\n|:E2 E BEB|EBE AFD|EDE B3|dcB AFD|\nE3 B3|EBE AFD|G3 FGA|BAG FED:|\nBee fee|aee fed|Bee fee|fag fed|\nBee fee|aee fef|gfe d2A|BAG FED|\nBee fee|aee fed|Bee fee|faf def|\ng2g gfe|defg2d|edc d2A|BAG FED|")
Note.create(tune_id: 7, user_id: 2, status:"public", key: "D", scale: "major", abc:"T: Father O'Flynn\nR: jig\nM: 6/8\nL: 1/8\nK: Dmaj\n|:A|dAF DFA|ded cBA|dcd efg|fdf ecA|\ndAF DFA|ded cBA|dcd efg fdd d2:|\n|:g|fdf fga|ecA ABc|dcd Bed|cAA A2 =c|\nBGB Bcd|AFD DFA|dcd efg|fdd d2:|")
Note.create(tune_id: 7, user_id: 4, status:"public", key: "D", scale: "major", abc:"T: Father O'Flynn\nR: jig\nM: 6/8\nL: 1/8\nK: Dmaj\nA|dAF DFA|ded cBA|dcd ede|fdf ecA|dAF DFA|\nded cBA|dcd ede|fdd d3|(fg)f fga|ecA A3|dcd Bed|\ncAA A3|BGB Bcd|AFD DFA|dcd ede|fdd d2||")
Note.create(tune_id: 7, user_id: 1, status:"public", key: "G", scale: "major", abc:"T: Father O'Flynn\nR: jig\nM: 6/8\nL: 1/8\nK: Dmaj\n|:A|dAF DFA|ded cBA|dcd efg|fdf ecA|\ndAF DFA|ded cBA|dcd efg|fdc d2:|\n|:g|fdf fga|ecA ABc|dcd Bed|cAA A2c|\nBGB Bcd|AFD DFA|dcd efg|1 fdf e2:|2 fdc d2||")
Note.create(tune_id: 8, user_id: 2, status:"public", key: "E", scale: "dorian", abc:"T: A Fig For A Kiss\nR: slip jig\nM: 9/8\nL: 1/8\nK: Edor\nF|G2B E2B BAG|FGA D2A AGF|GAB E2B BAG|BdB AGF E2F|\nG2B e2B BAG|FGA D2A AGF|GAB E2B BAG|BdB AGF E2f||\ng2e g2e edB|f2d dcd fga|g2e g2e edB|dBG GBd e2f|\ng2e g2e edB|f2d dcd fga|gfe agf edc|BdB AGF E2||")
Note.create(tune_id: 8, user_id: 4, status:"public", key: "E", scale: "dorian", abc:"T: A Fig For A Kiss\nR: slip jig\nM: 9/8\nL: 1/8\nK: Edor\nG2B E2B BAG|F2A D2A AFD|G2B E2B BAG|B/c/dB AGF E2F|\nG2B E2B BAG|F2A D2A AFD|G2B E2B BAG|B/c/dB AGF E3||\ng2e g2e edB|f3 dfa afd|g2e g2e edB|AB/c/d efd e2f|\ng2e g2e edB|f3 dfa afd|gfe agf gfe|dcB AGF E3||")
Note.create(tune_id: 9, user_id: 1, status:"public", key: "E", scale: "minor", abc:"T: The Butterfly\nR: slip jig\nM: 9/8\nL: 1/8\nK: Emin\n|:B2E G2E F3|B2E G2E FED|B2E G2E F3|B2d d2B AFD:|\n|:B2d e2f g3|B2d g2e dBA|B2d e2f g2a|b2a g2e dBA:|\n|:B3 B2A G2A|B3 BAB dBA|B3 B2A G2A|B2d g2e dBA:|")
Note.create(tune_id: 9, user_id: 3, status:"public", key: "E", scale: "minor", abc:"T: The Butterfly\nR: slip jig\nM: 9/8\nL: 1/8\nK: Emin\n|:B2E G2E F3|B2E G2E FED|B2E G2E F3|B2d d2B AFD:|\n|:B2c e2f g3|B2c g2e dBA|B2c e2f g2a|b2a g2e dBA:|\n|:B3 B2A G2A|B3 BAB dBA|B3 B2A G2A|B2d g2e dBA:|")
Note.create(tune_id: 10, user_id: 1, status:"public", key: "E", scale: "minor", abc:"T: The Kid On The Mountain\nR: slip jig\nM: 9/8\nL: 1/8\nK: Emin\n|:EDE FEF G2 F|EDE BcA BGE|EDE FEF G2 G/A/|BAG FAG FED:|\n|:BGB AFA G2 D|GAB dge dBG|BGB AFA G2 G/A/|BAG FAG FED:|\n|:gfg eBe e2 f|gfg efg afd|gfg eBe e2 g/a/|bag fag fed:|\n|:eBB e2f gfg|eBB efg afd|eBB e2f g2 g/a/|bag fag fed:|\n|:edB dBA G2D|GAB dge dBd|edB dBA G2 G/A/|BAG FAG FED:|")
Note.create(tune_id: 10, user_id: 2, status:"public", key: "G", scale: "major", abc:"T: The Kid On The Mountain\nR: slip jig\nM: 9/8\nL: 1/8\nK: Gmaj\n|:EDE FEF G2F|E3B2A BGE|EDE FEF G2 A|BAG FAG FED:|\n|:BGB AFA G2 D|GAB dge dBA|BGB AFAG2A|BAG FAG FED:|\n|:gfg eBe e2f|gfg efg afd|gfg eBe ega|bag fag fed:|\n|:eBB e2 f g2 f|eBB efg afd|eBB e2 f g2 a|bag fag fed:|\n|:edB dBA G2 D|GAB dge dBd|edB dBA G2 A|BAG FAG FED:|")
Note.create(tune_id: 11, user_id: 3, status:"public", key: "D", scale: "major", abc:"T: The Foxhunter\nR: slip jig\nM: 9/8\nL: 1/8\nK: Dmaj\n|:FDF F2D G2E|FDF F2D E2D|FDF F2D G2B|AFD DEF E2D:|\n|:B3 BAG FGA|B2E E2F G2B|ABc dcB ABc|d2 D D2 F E2 D:|\n|:fdf f2d g2e|fdf f2d e2d|fdf f2d g2b|afd def e2d:|\n|:gfe dcB AGF|B2 E E2 F G2 B|ABc dcB ABc|d2 D DEF E2 D:|")
Note.create(tune_id: 11, user_id: 4, status:"public", key: "D", scale: "major", abc:"T: The Foxhunter\nR: slip jig\nM: 9/8\nL: 1/8\nK: Dmaj\nFGF FDFG2 E|FGF FDFE2 D|FGF FDFG2 B|AFD DEFE2 D:|\nBcB BAG FGA|B2 EE2F G2 B|ABc dcB ABc|d2 D DEFE2 D:|\nfgf fdf g2 e|fgf fdfe2 d|fgf fdfg2 b|afd def e2 d:|\ngfe dcB AGA|B2 EE2 FG2 B|ABc dcB ABc|d2 D DEF E2 D:|")
Note.create(tune_id: 12, user_id: 4, status:"public", key: "D", scale: "major", abc:"T: The Wise Maid\nR: reel\nM: 4/4\nL: 1/8\nK: Dmaj\n|:DE|F2FG FEDE|FAAB AFED|d2eg fdec|dBAG BEED|\nF2FG FEDE|FAAB AFED|d2eg fdec|dBAG FD:|\n|:FA|d2AG FDFA|dfaf gfeg|fedf eAcA|dfed cA A2|\nBAGB ADFD|dfaf gfed|Bdce dBAG|FGEF D2:|\n")
Note.create(tune_id: 13, user_id: 3, status:"public", key: "G", scale: "major", abc:"T: Christmas Eve\nR: reel\nM: 4/4\nL: 1/8\nK: Gmaj\n|:GE|D3E ~G3A|B2dB ABGA|BAGE DB,DE|GABG ABGE|\nDB,DE ~G3A|B2dB ABGA|BAAB GE~E2|ABGE G2:|\n|:GA|BA (3Bcd edeg|abge g2eg|a2ge ~g3e|dedB ABGA|\nBA (3Bcd edeg|abge g2eg|abge d2BG|ABGE G2:|\n|:dc|BG~G2 dG (3Bcd|eg~g2 egdc|BG~G2 DGBG|EAAG EAAc|\nBG~G2 dG (3Bcd|eg~g2 egdg|bgag eddB|ABGE G2:|")
Note.create(tune_id: 14, user_id: 1, status:"public", key: "A", scale: "dorian", abc:"T: The Congress\nR: reel\nM: 4/4\nL: 1/8\nK: Ador\n|:eAAG A2 B/c/d|eaaf gedg|eAA2 eAcA|BGGF GABd|\neAAG A2 B/c/d|eaaf gedB|cBcd eged|cABG A2 B/c/d:|\n|:eaag a3g|eaaf gedg|egdg egdg|eaaf gedg|\neaag a3g|eaaf gedB|cBcd eged|cABG A2 B/c/d:|")
Note.create(tune_id: 14, user_id: 4, status:"public", key: "A", scale: "dorian", abc:"T: The Congress\nR: reel\nM: 4/4\nL: 1/8\nK: Ador\n|:eAAG A2 B/c/d|eaaf gedg|eAA2 eAcA|BGGF GABd|\neAAG A2 B/c/d|eaaf gedB|cBcd eged|cABG A2 B/c/d:|\n|:eaag a3g|eaaf gedg|egdg egdg|eaaf gedg|\neaag a3g|eaaf gedB|cBcd eged|cABG A2 B/c/d:|")
Note.create(tune_id: 15, user_id: 2, status:"public", key: "E", scale: "dorian", abc:"T: Drowsy Maggie\nR: reel\nM: 4/4\nL: 1/8\nK: Edor\n|:E2BE dEBE|E2BE AFDF|E2BE dEBE|BABc dAFD:|\nd2fd c2ec|defg afge|d2fd c2ec|BABc dAFA|\nd2fd c2ec|defg afge|afge fdec|BABc dAFD|")
Note.create(tune_id: 15, user_id: 3, status:"public", key: "E", scale: "dorian", abc:"T: Drowsy Maggie\nR: reel\nM: 4/4\nL: 1/8\nK: Edor\n|:E2BE dEBE|E2BE AFDF|E2BE dEBE|BABc dAFD:|\nd2fd cdec|defg afge|d2fd cdec|BABc dAFA|\nd2fd c2ec|defg afga|bgaf gfed|BABc dAFD|")
Note.create(tune_id: 15, user_id: 4, status:"public", key: "E", scale: "dorian", abc:"T: Drowsy Maggie\nR: reel\nM: 4/4\nL: 1/8\nK: Edor\n|:E2BE dEBE|E2BE AFDF|E2BE dEBE|B2Bc dAFD:|\ndefd cdec|defg afge|d2fd cdec|B2Bc dAFA|\ndefd cdec|defg a2eg|afge fdec|dBAG FDED|")
Note.create(tune_id: 16, user_id: 1, status:"public", key: "D", scale: "major", abc:"T: The Wind That Shakes The Barley\nR: reel\nM: 4/4\nL: 1/8\nK: Dmaj\nA2AB AFED|B2BA BcdB|A2AB AFED|gfed BcdB|\nA2AB AFED|B2BA BcdB|A2AB AFED|gfed Bcde||\nf2fd g2ge|f2fd Bcde|f2fd g2fg|afed Bcde|\nf2fd g2ge|f2fd Bcde|defg a2ab|afed BcdB||")
Note.create(tune_id: 16, user_id: 3, status:"public", key: "D", scale: "major", abc:"T: The Wind That Shakes The Barley\nR: reel\nM: 4/4\nL: 1/8\nK: Dmaj\nA2AB AFED|B2BA BcdB|A2AB ABde|1 fedc BcdB:|2 fedc Bcde||\nf2fd g2ge|f2fd Bcde|f2fd g2fg|afed Bcde|\nf2fd g2ge|f2fd Bcde|defg a2ab|afed BcdB||")
Note.create(tune_id: 16, user_id: 4, status:"public", key: "D", scale: "major", abc:"T: The Wind That Shakes The Barley\nR: reel\nM: 4/4\nL: 1/8\nK: Dmaj\nA2AB AFED|B2BA Bcd2|A2AB AFED|gfed BcdB|\nA2AB AFED|B2BA BcdB|A2AB AFED|gfed Bcde||\nf2fd g2ge|f2fd edBd|f2fd g2ab|afed Bcde|\nf2fd g2ge|f2fd edBd|defg afbf|gfed BcdB||")

Note.create(tune_id: , user_id: 4, status:"public", key: "D", scale: "major", abc:"T: John Ryan's\nR: polka\nM: 2/4\nL: 1/8\nK: Dmaj\ndd B/c/d/B/|AF ED|dd B/c/d/B/|AF E2|\ndd B/c/d/B/|AF Ad|fd ec|d2 d2||\nfd de/f/|gf ed|fd de/f/|gf a2|\nfd de/f/|gf ed|fd ec|d2 d2|| ")
Note.create(tune_id: , user_id: 4, status:"public", key: "D", scale: "miner", abc:"T: Tam Lin\nR: reel\nM: 4/4\nL: 1/8\nK: Dmin\nA,2DA, FA,DA,|B,2DB, FB,DB,|C2EC GCEC|FEDC A,DDC|\nA,2DA, FA,DA,|B,2DB, FB,DB,|C2EC GCEC|FEDC A,DD2:|\n|:dA~A2 FADA|dA~A2 FADA|cG~G2 EG~G2|cG~G2 cdec|\ndA~A2 FADA|dA~A2 FADA,|~B,3A, B,CDE|FDEC A,DD2:| ")
Note.create(tune_id: , user_id: 4, status:"public", key: "B", scale: "miner", abc:"T: Tam Lin\nR: reel\nM: 4/4\nL: 1/8\nK: Bmin\nF2 BF dFBF|G2 BG dGBG|A2 cA eAcA|dcBA FBBA|\nF2 BF dFBF|G2 BG dGBG|A2 cA eAcA|dcBA FB B2:|\nbf ~f2 dfBf|bf ~f2 dfBf|ae ~e2 ce ~e2|ae ~e2 abc'a|\nbf ~f2 dfBf|bf ~f2 dfBF|~G3 F GABc|dBcA FB B2:| ")
Note.create(tune_id: , user_id: 4, status:"public", key: "E", scale: "dorian", abc:"T: A Fig For A Kiss\nR: slipjig\nM: 9/8\nL: 1/8\nK: Edor\nG2B E2B BAG|F2A D2A AGF|G2B E2B BAG|B/c/dB AGF DEF|\nG2B E2B BAG|F2A D2A AGF|G2B E2B BAG|B/c/dB AGF E3||\ng2e g2e edB|f2d dcd fed|g2e g2e edB|dBG GBd e2f|\ng2e g2e edB|f2d dcd fed|gfe fed ecA|B/c/dB AGF E2F|| ")
Note.create(tune_id: , user_id: 1, status:"public", key: "G", scale: "major", abc:"T: The Kesh\nR: jig\nM: 6/8\nL: 1/8\nK: Gmaj\n|:G3 GAB|A3 ABd|edd gdd|edB dBA|\nGAG GAB|ABA ABd|edd gdd|BAF G3:|\n|:B2B d2d|ege dBA|B2B dBG|ABA AGA|\nBAB d^cd|ege dBd|gfg aga|bgg g3:| ")
Note.create(tune_id: , user_id: 4, status:"public", key: "D", scale: "major", abc:"T: John Ryan's\nR: polka\nM: 2/4\nL: 1/8\nK: Dmaj\n|:dd B/c/d/B/|AF AF|dd B/c/d/B/|AF ED|\ndd B/c/d/B/|AF Ad/e/|fd ec|1 df d2:|2 df dd/e/||\n|:fd de/f/|g>f ed/e/|fd Ad|fd/f/ a>g|\nfd- de/f/|g/a/g/f ed/e/|fd ed/c/|1 d2 d>e:|2 d2 d2|| ")
Note.create(tune_id: , user_id: 4, status:"public", key: "D", scale: "major", abc:"T: Fisher's\nR: hornpipe\nM: 4/4\nL: 1/8\nK: Dmaj\n|:(3ABc|'D' dAFD 'G' GBAG|'D' FDFD 'G' GBAG|'D' FDFD 'G' GBAG|'D' FDFD 'A' E2 (3ABc|\n'D' dAFD 'G' GBAG|'D' FDFD 'G' GBAG|'D' FGAB cdec|d2 d/e/d/c/ d2:|\n|:cd|'A' ecAc efge|'D' fdAd fgaf|'A' ecAc efgf|edcB A2 A2|\n'D' BGDG BdcB|'G' AFDF A2 GA|'D' BdcB 'A' AGFE|'D'D2 d2 D2:| ")
Note.create(tune_id: , user_id: 4, status:"public", key: "D", scale: "major", abc:"T: John Ryan's\nR: polka\nM: 2/4\nL: 1/8\nK: Dmaj\ndd B/c/d/B/|AF ED|dd B/c/d/B/|AF E2|\ndd B/c/d/B/|AF Ad|fd ec|d2 d2||\nfd de/f/|gf ed|fd de/f/|gf a2|\nfd de/f/|gf ed|fd ec|d2 d2|| ")
Note.create(tune_id: , user_id: 4, status:"public", key: "D", scale: "miner", abc:"T: Tam Lin\nR: reel\nM: 4/4\nL: 1/8\nK: Dmin\nA,2DA, FA,DA,|B,2DB, FB,DB,|C2EC GCEC|FEDC A,DDC|\nA,2DA, FA,DA,|B,2DB, FB,DB,|C2EC GCEC|FEDC A,DD2:|\n|:dA~A2 FADA|dA~A2 FADA|cG~G2 EG~G2|cG~G2 cdec|\ndA~A2 FADA|dA~A2 FADA,|~B,3A, B,CDE|FDEC A,DD2:| ")
Note.create(tune_id: , user_id: 4, status:"public", key: "B", scale: "miner", abc:"T: Tam Lin\nR: reel\nM: 4/4\nL: 1/8\nK: Bmin\nF2 BF dFBF|G2 BG dGBG|A2 cA eAcA|dcBA FBBA|\nF2 BF dFBF|G2 BG dGBG|A2 cA eAcA|dcBA FB B2:|\nbf ~f2 dfBf|bf ~f2 dfBf|ae ~e2 ce ~e2|ae ~e2 abc'a|\nbf ~f2 dfBf|bf ~f2 dfBF|~G3 F GABc|dBcA FB B2:| ")
Note.create(tune_id: , user_id: 4, status:"public", key: "E", scale: "dorian", abc:"T: A Fig For A Kiss\nR: slipjig\nM: 9/8\nL: 1/8\nK: Edor\nG2B E2B BAG|F2A D2A AGF|G2B E2B BAG|B/c/dB AGF DEF|\nG2B E2B BAG|F2A D2A AGF|G2B E2B BAG|B/c/dB AGF E3||\ng2e g2e edB|f2d dcd fed|g2e g2e edB|dBG GBd e2f|\ng2e g2e edB|f2d dcd fed|gfe fed ecA|B/c/dB AGF E2F|| ")